trigger:
- dev
- release/*

phases:
- phase: Windows
  queue: Hosted VS2017
  steps:
  - script: build.cmd -ci
  - task: PublishTestResults@2
    inputs:
      testRunner: vstest
      testResultsFiles: 'artifacts/logs/**/*.trx'

- phase: macOS
  queue: Hosted macOS Preview
  steps:
  - script: ./build.sh --ci

- phase: Linux
  queue: Hosted Linux Preview
  steps:
  - script: ./build.sh --ci
