trigger:
- dev
- release/*

phases:
- phase: Windows
  queue:
    demands: cmd
  steps:
  - script: build.cmd -ci
  - task: PublishTestResults@2
    condition: always()
    inputs:
      testRunner: vstest
      testResultsFiles: 'artifacts/logs/**/*.trx'


- phase: macOS
  queue:
    demands: agent.os -equals Darwin
  steps:
  - script: ./build.sh --ci

- phase: Linux
  queue:
    demands: agent.os -equals Linux
  steps:
  - script: ./build.sh --ci
