trigger:
- dev
- release/*

phases:
- phase: Windows
  queue: Hosted VS2017
  steps:
  - script: build.cmd -ci

- phase: macOS
  queue: Hosted macOS Preview
  steps:
  - script: ./build.sh --ci

- phase: Linux
  queue: Hosted Linux Preview
  steps:
  - script: ./build.sh --ci
